FIGSIZE_1 = (5, 6)
FIGSIZE_2 = (10, 6)
FIGSIZE_3 = (14, 6)

SLIDER_CENTER_X = 0.5
SLIDER_CENTER_Y = 0.03
SLIDER_WIDTH = 0.8
SLIDER_HEIGHT = 0.02
SLIDER_GEOMETRY = [
    SLIDER_CENTER_X - SLIDER_WIDTH / 2,
    SLIDER_CENTER_Y - SLIDER_HEIGHT / 2,
    SLIDER_WIDTH,
    SLIDER_HEIGHT
]

COLORBAR_CENTER_X = 0.5
COLORBAR_CENTER_Y = 0.93
COLORBAR_HEIGHT = 0.02
COLORBAR_WIDTH = 0.4
COLORBAR_GEOMETRY = [
    COLORBAR_CENTER_X - COLORBAR_WIDTH / 2,
    COLORBAR_CENTER_Y - COLORBAR_HEIGHT / 2,
    COLORBAR_WIDTH,
    COLORBAR_HEIGHT
]
