exec = python3
# exec = ipython -i --no-confirm-exit

1:
	cd "./01 - Discretize mass axis." && $(exec) main.py
11:
	cd "./11 - Plot kernel from settings specified in config file." && $(exec) main.py
12:
	cd "./12 - Plot kernel for basic hit-and-stick coagulation on linear mass axis with a small mass range." && $(exec) main.py
13:
	cd "./13 - Plot kernel for basic hit-and-stick coagulation on linear mass axis." && $(exec) main.py
14:
	cd "./14 - Plot kernel for basic hit-and-stick coagulation on logarithmic mass axis." && $(exec) main.py
15:
	cd "./15 - Plot kernel comparison: Kees' kernel vs. mine." && $(exec) main.py
16:
	cd "./16 - Plot kernel comparison: linear vs. logarithmic mass axis." && $(exec) main.py
17:
	cd "./17 - Test mass conservation." && $(exec) main.py
18:
	cd "./18 - Plot kernel for basic fragmentation on linear mass axis." && $(exec) main.py
19:
	cd "./19 - Plot kernel for basic fragmentation on logarithmic axis." && $(exec) main.py
21:
	cd "./21 - Model collision cross sections." && $(exec) main.py
22:
	cd "./22 - Model relative particle velocities." && $(exec) main.py
23:
	cd "./23 - Model collision rates." && $(exec) main.py
31:
	cd "./31 - Integrate explicitly on linear grid." && $(exec) main.py
32: 
	cd "./32 - Integrate explicitly on logarithmic grid." && $(exec) main.py
33:
	cd "./33 - Integrate implicitly on logarithmic grid." && $(exec) main.py
61:
	cd "./61 - Model disk properties as a function of distance from star." && $(exec) main.py
62:
	cd "./62 - Model disk properties as a function of dust particle mass." && $(exec) main.py
