#!../.venv/bin/python3
import os, re, sys
from termcolor import colored


NR_OF_TERMINAL_COLS = os.get_terminal_size().columns
TITLE = "VINCENTMADER/MSC-THESIS.PY"
NR_OF_BORDER_CHARS = NR_OF_TERMINAL_COLS - 5
TOP_LINE = '─' * NR_OF_BORDER_CHARS
PAD_LEFT = ((NR_OF_TERMINAL_COLS - 5 - len(TITLE)) // 2) * ' '
PAD_RIGHT = PAD_LEFT if NR_OF_TERMINAL_COLS % 2 != 0 else PAD_LEFT + ' '
LINE_1 = f"╭─{TOP_LINE}─╮"
LINE_2 = f"│ {PAD_LEFT}{TITLE}{PAD_RIGHT} │"
LINE_3 = f"╰─{TOP_LINE}─╯"
INFO_TEXT_1 = f"""\
 {colored(LINE_1, "blue")}
 {colored(LINE_2, "blue")}
 {colored(LINE_3, "blue")}\n
 Below, you find a list of examples on how to use this library:
"""

INFO_TEXT_2 = f"""
 To run one of the examples, please enter the corresponding example ID 
 (highlighted in {colored("green", "green")}) in the prompt below,\
 and confirm with the <Enter> key.
 
 By default, the example will be run using `../.venv/bin/python3`.
 If, instead, you would like to use iPython, just append an `i` to the ID.
 
 Example: `./run 22i` would execute example 22 in interactive python mode.
"""


def get_example_directories():
    dirs = os.listdir('.')
    dirs = sorted(dirs)
    dirs = filter(is_valid_example_directory_name, dirs)
    dirs = { parse_dir_to_int(d): d for d in dirs }
    return dirs


def get_example_id(examples):

    def get_example_id_from_cli_arg():
        return sys.argv[1]
    
    def get_example_id_from_user_input(examples):
        print(INFO_TEXT_1)
        for example_id, dir_name in examples.items():
            split = dir_name.split(" - ")
            if example_id < 10:
                example_id = f" {example_id}"
            example_id = colored(example_id, "green")
            example_name = split[1]
            text = " " + " - ".join([example_id, example_name])
            print(text)
        print(INFO_TEXT_2)
        return input(colored(" >> ", "blue"))

    if len(sys.argv) > 1:
        return get_example_id_from_cli_arg()
    else:
        return get_example_id_from_user_input(examples)


def unpack_example_id(example_id):
    interactive_python = example_id.endswith('i')
    if interactive_python:
        example_id = example_id[:-1]
    return int(example_id), interactive_python  # todo: Handle parse error.


def get_example_from_id(examples, example_id):
    example = examples[example_id]  # todo: Handle index error.
    return example


def run_example(example, interactive_python):
    if interactive_python:
        python = "ipython -i --no-confirm-exit"
    else:
        python = "../../.venv/bin/python3"
    cmd = f"cd \"{example}\" && {python} main.py"
    os.system(cmd)


def is_valid_example_directory_name(dir_name):
    """Filter directory names: Keep valid examples."""
    if re.search(" - ", dir_name) is None:
        return False
    return True


def parse_dir_to_int(x):
    """Convert example directory name to integer example-id."""
    x = x.split(" - ")[0]
    x = int(x)
    return x


if __name__ == "__main__":
    os.system("clear")
    examples = get_example_directories()
    example_id = get_example_id(examples)
    example_id, interactive_python = unpack_example_id(example_id)
    example = get_example_from_id(examples, example_id)
    run_example(example, interactive_python)
